apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: csi-snapshot-controller
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: CSISnapshot
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
  - name: csi-snapshot-controller
    version: "0.0.1-snapshot"
spec: {}
